/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { ZeroCustomType } from "drizzle-zero"
import type { default as zeroSchema } from "../../database/drizzle-zero.config"

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    feedItems: {
      name: "feedItems",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feedItems", "id">,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feedItems", "createdAt">,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feedItems", "updatedAt">,
          serverName: "updated_at",
        },
        kind: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feedItems", "kind">,
        },
        feedSourceId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feedItems", "feedSourceId">,
          serverName: "feed_source_id",
        },
      },
      primaryKey: ["id"],
      serverName: "feed_items",
    },
    feeds: {
      name: "feeds",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "id">,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "createdAt">,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "updatedAt">,
          serverName: "updated_at",
        },
        kind: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "kind">,
        },
        url: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "url">,
        },
        title: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "title">,
        },
        lastFetchedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "lastFetchedAt">,
          serverName: "last_fetched_at",
        },
        lastFetchError: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "feeds", "lastFetchError">,
          serverName: "last_fetch_error",
        },
      },
      primaryKey: ["id"],
    },
    rssArticles: {
      name: "rssArticles",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "id">,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "createdAt">,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "updatedAt">,
          serverName: "updated_at",
        },
        rssFeedId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "rssFeedId">,
          serverName: "rss_feed_id",
        },
        feedItemId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "feedItemId">,
          serverName: "feed_item_id",
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "title">,
        },
        link: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "link">,
        },
        content: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "content">,
        },
        summary: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "summary">,
        },
        pubDate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "pubDate">,
          serverName: "pub_date",
        },
        author: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "author">,
        },
        metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssArticles", "metadata">,
        },
      },
      primaryKey: ["id"],
      serverName: "rss_articles",
    },
    rssFeeds: {
      name: "rssFeeds",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "id">,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "createdAt">,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "updatedAt">,
          serverName: "updated_at",
        },
        feedId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "feedId">,
          serverName: "feed_id",
        },
        siteUrl: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "siteUrl">,
          serverName: "site_url",
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "description">,
        },
        imageUrl: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "imageUrl">,
          serverName: "image_url",
        },
        language: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "language">,
        },
        metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssFeeds", "metadata">,
        },
      },
      primaryKey: ["id"],
      serverName: "rss_feeds",
    },
    rssPodcasts: {
      name: "rssPodcasts",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "id">,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "createdAt">,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "updatedAt">,
          serverName: "updated_at",
        },
        rssFeedId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "rssFeedId">,
          serverName: "rss_feed_id",
        },
        feedItemId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "feedItemId">,
          serverName: "feed_item_id",
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "title">,
        },
        link: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "link">,
        },
        audioUrl: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "audioUrl">,
          serverName: "audio_url",
        },
        duration: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "duration">,
        },
        pubDate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "pubDate">,
          serverName: "pub_date",
        },
        showNotes: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "showNotes">,
          serverName: "show_notes",
        },
        guest: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "guest">,
        },
        metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, "rssPodcasts", "metadata">,
        },
      },
      primaryKey: ["id"],
      serverName: "rss_podcasts",
    },
  },
  relationships: {},
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
