import { drizzleZeroConfig } from "drizzle-zero"
import { schema } from "./src"

export default drizzleZeroConfig(schema, {
  tables: {
    account: false,
    session: false,
    user: false,
    verification: false,
    feeds: {
      id: true,
      createdAt: true,
      updatedAt: true,
      lastFetchError: true,
      kind: true,
      url: true,
      title: true,
      lastFetchedAt: true,
    },
    rssFeeds: {
      id: true,
      createdAt: true,
      updatedAt: true,
      metadata: true,
      feedId: true,
      siteUrl: true,
      description: true,
      imageUrl: true,
      language: true,
    },
    feedItems: {
      id: true,
      createdAt: true,
      updatedAt: true,
      kind: true,
      feedSourceId: true,
    },
    rssArticles: {
      id: true,
      createdAt: true,
      updatedAt: true,
      feedItemId: true,
      title: true,
      link: true,
      author: true,
      content: true,
      summary: true,
      metadata: true,
      rssFeedId: true,
      pubDate: true,
    },
    rssPodcasts: {
      id: true,
      createdAt: true,
      updatedAt: true,
      feedItemId: true,
      title: true,
      link: true,
      audioUrl: true,
      duration: true,
      pubDate: true,
      showNotes: true,
      guest: true,
      metadata: true,
      rssFeedId: true,
    },
  },
})
